### PR TITLE
fix: change groups layout via bootstrap v3

### PR DESCRIPTION
**Pull request by amautadev**

### CODE REVIEW

**Comment by amautadev** [comment]
image
locally it behaves as prod ui. 
I have rewrote classes span4 with bootstrap v3 version

**Comment by steveoni** [comment]
The ui now looks very good. just some small little things to update

* the top navbar not visible in dev
prod
image

dev
image

* blog page layout (for this you can confirm if odni custom CSS interact with this or it just that the plugin has change its layout compared to the previous version)

prod
image


dev

image


@AlmubdyMutaikhan

**Comment by amautadev** [comment]
@steveoni `the top navbar not visible in dev`
could you please clarify this moment? I coudn't get the meaning, these two images seem to be same

**Comment by steveoni** [comment]
> @steveoni `the top navbar not visible in dev` could you please clarify this moment? I coudn't get the meaning, these two images seem to be same

prod 
image

dev
image

if you move your mouse across the user profile to the left, you will see some not visible icons

**Comment by amautadev** [comment]
> prod

Can you share then prod and dev admin login and password, so I can see these things, please

**Comment by steveoni** [comment]
> > prod
> 
> Can you share then prod and dev admin login and password, so I can see these things, please

check your chat

**Comment by amautadev** [comment]
image
for blog news I applied new styles changes. This was rather custom styles issues

**Comment by amautadev** [comment]
[@steveoni1](https://github.com/steveoni1) I have investigated the icons rendering and it turns out to be in newer bootstrap icons removed. I tried to render with glyphicons, which was successful, but only for several of them. I think we need to consider a new library or a new cdn.

**Comment by AlmubdyMutaikhan** [comment]
image
so far I changed one icon and added one email icon. what do you thin of them?

**Comment by amautadev** [comment]
@steveoni 
image
what do you think of navbar now?

**Pull request merged**
